/**
 * Configuración estática para el módulo SIG - Sección: Políticas
 */

export const POLITICAS_ITEMS = [
    {
        id: 'politica_sig',
        label: 'Política Sistema Integrado de Gestión',
        description: 'Compromiso institucional con la calidad, medio ambiente y seguridad en el trabajo.',
        type: 'document',
        file: 'https://dynamics.appceg.com/sig/INTRANET%20BOTONES/E02.D002%20Pol%C3%ADtica%20sistema%20integrado%20de%20gesti%C3%B3n.pdf',
        category: 'Institucional',
    },
    {
        id: 'politica_prevencion',
        label: 'Política de prevención',
        description: 'Lineamientos para la prevención de consumo de alcohol, tabaco y sustancias psicoactivas.',
        type: 'document',
        file: 'https://dynamics.appceg.com/sig/INTRANET%20BOTONES/A01.D001%20Pol%C3%ADtica%20de%20prevenci%C3%B3n%20del%20consumo%20de%20alcohol,%20drogas%20y%20tabaco.pdf',
        category: 'Prevención',
    },
    {
        id: 'manual_datos_personales',
        label: 'Manual de datos personales',
        description: 'Políticas y procedimientos para la protección y tratamiento de datos personales (Habeas Data).',
        type: 'document',
        file: 'https://dynamics.appceg.com/sig/INTRANET%20BOTONES/E01.M001%20Manual%20de%20pol%C3%ADticas%20y%20procedimientos%20tratamiento%20de%20datos.pdf',
        category: 'Habeas Data',
    },
    {
        id: 'politica_seguridad_vial',
        label: 'Política de seguridad vial',
        description: 'Lineamientos para la prevención de accidentes y seguridad en el transporte.',
        type: 'document',
        file: 'https://dynamics.appceg.com/sig/INTRANET%20BOTONES/A01.D004%20Pol%C3%ADtica%20de%20seguridad%20vial.pdf',
        category: 'SST',
    },
    {
        id: 'politica_seguridad_informatica',
        label: 'Política de seguridad informática',
        description: 'Normas y buenas prácticas para la seguridad de la información y activos TI.',
        type: 'document',
        file: 'https://dynamics.appceg.com/sig/INTRANET%20BOTONES/A02.D005%20Pol%C3%ADtica%20de%20seguridad%20inform%C3%A1tica.pdf',
        category: 'Tecnología',
    },
    {
        id: 'politica_privacidad',
        label: 'Política de privacidad',
        description: 'Principios y privacidad en el manejo de la información institucional.',
        type: 'document',
        file: 'https://dynamics.appceg.com/sig/INTRANET%20BOTONES/A03.D003%20Pol%C3%ADtica%20de%20privacidad.pdf',
        category: 'Privacidad',
    },
    {
        id: 'politica_firmas_sellos',
        label: 'Política de firmas y sellos',
        description: 'Reglamento para la autorización, control y uso de firmas y sellos oficiales.',
        type: 'document',
        file: 'https://dynamics.appceg.com/sig/INTRANET%20BOTONES/E02.D004%20Pol%C3%ADtica%20de%20firmas%20y%20sellos.pdf',
        category: 'Gobierno',
    },
    {
        id: 'politica_control_seguridad',
        label: 'Política de control y seguridad',
        description: 'Sistema de gestión en control y seguridad institucional.',
        type: 'document',
        file: 'https://dynamics.appceg.com/sig/INTRANET%20BOTONES/E02.D011%20Pol%C3%ADtica%20de%20control%20y%20seguridad.pdf',
        category: 'Seguridad',
    },
    {
        id: 'politica_contratacion',
        label: 'Política de contratación - Salarial y Beneficios',
        description: 'Criterios de contratación, compensación y beneficios para colaboradores.',
        type: 'document',
        file: 'https://dynamics.appceg.com/sig/INTRANET%20BOTONES/V01.D019%20Politica%20de%20contrataci%C3%B3n%20%E2%80%93%20Salarial%20y%20Beneficios.pdf',
        category: 'Gestión Humana',
    },
    {
        id: 'codigo_etica',
        label: 'Código de ética',
        description: 'Valores, principios y conducta esperada en la organización.',
        type: 'document',
        file: 'https://dynamics.appceg.com/sig/INTRANET%20BOTONES/A01.P016%20C%C3%B3digo%20de%20%C3%A9tica.pdf',
        category: 'Institucional',
    },
    {
        id: 'reglamento_interno',
        label: 'Reglamento interno de trabajo',
        description: 'Reglamento regulador de relaciones laborales y convivencia.',
        type: 'document',
        file: 'https://dynamics.appceg.com/sig/INTRANET%20BOTONES/reglamento%20interno.pdf',
        category: 'Laboral',
    },
];
